[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "BASE_URL,EMAIL_HOST,PORT,GOOGLE_CALLBACK_URL,MAXIMUM_SINGLE_PAYMENT,CORS_ORIGIN,REDIS_PORT,CLIENT_URL,FRONTEND_URL,MINIMUM_PAYOUT,PLATFORM_FEE_PERCENTAGE,STRIPE_API_VERSION,WEBHOOK_URL,META_CALLBACK_URL,TIKTOK_CALLBACK_URL,TWITTER_CALLBACK_URL,YOUTUBE_CALLBACK_URL,EMAIL_PORT,EMAIL_USER,REDIS_HOST"
